apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/address-pool: wordpress-ip
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: wordpress
    port: 5050

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: services_wordpress
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_SERV
          valueFrom:
            configMapKeyRef:
              name: mysql-servaddr
              key: mysql-servaddr
        - name: WP_DB
          valueFrom:
            configMapKeyRef:
              name: wordpress-dbname
              key: wordpress-dbname
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /tmp/liveness.sh
          initialDelaySeconds: 15
          periodSeconds: 20
