apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  ports:
  - port: 4999
    protocol: TCP
    name: http
  selector:
    app: telegraf

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: services_telegraf
        ports:
        imagePullPolicy: Never
        env:
        - name: INFLUX_USER
          valueFrom:
            secretKeyRef:
              name: influx-secret
              key: user
        - name: INFLUX_PASS
          valueFrom:
            secretKeyRef:
              name: influx-secret
              key: password
        - name: MINIKUBE_IP
          valueFrom:
            configMapKeyRef:
              name: minikube-ip
              key: minikube-ip
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /tmp/liveness.sh
          initialDelaySeconds: 15
          periodSeconds: 20

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-rbac
  namespace: default
rules:
- apiGroups: [ "", "extensions", "apps" ]
  resources: [ "daemonsets", "deployments", "endpoints", "ingresses", "nodes", "persistentvolumes", "persistentvolumeclaims", "pods", "services", "statefulsets" ]
  verbs: [ "get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-rbac
  namespace: default
roleRef:
  kind: Role
  name: role-rbac
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
