apiVersion: v1
kind: Service
metadata:
  name: pma
  annotations:
    metallb.universe.tf/address-pool: phpmyadmin-ip
  labels:
    app: pma
spec:
  type: LoadBalancer
  selector:
    app: pma
  ports:
  - name: pma
    port: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
spec:
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: services_pma
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /tmp/liveness.sh
          initialDelaySeconds: 15
          periodSeconds: 20
